version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${RAILS_DB_PASSWORD}
      MYSQL_DATABASE: ${RAILS_DATABASE_NAME}
      MYSQL_USER: ${DOCKER_DB_USER_NAME}
      MYSQL_PASSWORD: ${RAILS_DB_PASSWORD}
    ports:
      - "3306:3306"

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      discovery.type: single-node
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      OPENSEARCH_SECURITY_SSL_HTTP_ENABLED: "false"
      OPENSEARCH_PLUGINS_SECURITY_DISABLED: "true"
      OPENSEARCH_USERNAME: ${DOCKER_OPENSEARCH_USERNAME}
      OPENSEARCH_PASSWORD: ${DOCKER_OPENSEARCH_PASSWORD}
      # Install kuromoji plugin on startup
      OPENSEARCH_PLUGINS_INSTALL: "analysis-kuromoji"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: "http://opensearch:9200"
      OPENSEARCH_SECURITY_SSL_HTTP_ENABLED: "false"
      OPENSEARCH_USERNAME: ${DOCKER_OPENSEARCH_USERNAME}
      OPENSEARCH_PASSWORD: ${DOCKER_OPENSEARCH_PASSWORD}

  web:
    build: .
    container_name: rails
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql2://${RAILS_DB_USER_NAME}:${RAILS_DB_PASSWORD}@db/${RAILS_DATABASE_NAME}
      ELASTICSEARCH_URL: http://opensearch:9200
    depends_on:
      - db
      - opensearch

volumes:
  db_data:
  opensearch-data: